#ifndef __AUTOGENCTOJSXCBENUMS__
#define __AUTOGENCTOJSXCBENUMS__
#include <v8.h>

namespace XCBJS {
  namespace Enum {

void Init(v8::Persistent<v8::Object> enums) {
  v8::Local<v8::Object> VisualClassObj = v8::Object::New();
  enums->Set(v8::String::New("VisualClass"), VisualClassObj);
  VisualClassObj->Set(v8::String::New("StaticGray"), v8::Integer::New(0));
  VisualClassObj->Set(v8::String::New("GrayScale"), v8::Integer::New(1));
  VisualClassObj->Set(v8::String::New("StaticColor"), v8::Integer::New(2));
  VisualClassObj->Set(v8::String::New("PseudoColor"), v8::Integer::New(3));
  VisualClassObj->Set(v8::String::New("TrueColor"), v8::Integer::New(4));
  VisualClassObj->Set(v8::String::New("DirectColor"), v8::Integer::New(5));
  v8::Local<v8::Object> EventMaskObj = v8::Object::New();
  enums->Set(v8::String::New("EventMask"), EventMaskObj);
  EventMaskObj->Set(v8::String::New("NoEvent"), v8::Integer::New(0));
  EventMaskObj->Set(v8::String::New("KeyPress"), v8::Integer::New(1));
  EventMaskObj->Set(v8::String::New("KeyRelease"), v8::Integer::New(2));
  EventMaskObj->Set(v8::String::New("ButtonPress"), v8::Integer::New(4));
  EventMaskObj->Set(v8::String::New("ButtonRelease"), v8::Integer::New(8));
  EventMaskObj->Set(v8::String::New("EnterWindow"), v8::Integer::New(16));
  EventMaskObj->Set(v8::String::New("LeaveWindow"), v8::Integer::New(32));
  EventMaskObj->Set(v8::String::New("PointerMotion"), v8::Integer::New(64));
  EventMaskObj->Set(v8::String::New("PointerMotionHint"), v8::Integer::New(128));
  EventMaskObj->Set(v8::String::New("Button1Motion"), v8::Integer::New(256));
  EventMaskObj->Set(v8::String::New("Button2Motion"), v8::Integer::New(512));
  EventMaskObj->Set(v8::String::New("Button3Motion"), v8::Integer::New(1024));
  EventMaskObj->Set(v8::String::New("Button4Motion"), v8::Integer::New(2048));
  EventMaskObj->Set(v8::String::New("Button5Motion"), v8::Integer::New(4096));
  EventMaskObj->Set(v8::String::New("ButtonMotion"), v8::Integer::New(8192));
  EventMaskObj->Set(v8::String::New("KeymapState"), v8::Integer::New(16384));
  EventMaskObj->Set(v8::String::New("Exposure"), v8::Integer::New(32768));
  EventMaskObj->Set(v8::String::New("VisibilityChange"), v8::Integer::New(65536));
  EventMaskObj->Set(v8::String::New("StructureNotify"), v8::Integer::New(131072));
  EventMaskObj->Set(v8::String::New("ResizeRedirect"), v8::Integer::New(262144));
  EventMaskObj->Set(v8::String::New("SubstructureNotify"), v8::Integer::New(524288));
  EventMaskObj->Set(v8::String::New("SubstructureRedirect"), v8::Integer::New(1048576));
  EventMaskObj->Set(v8::String::New("FocusChange"), v8::Integer::New(2097152));
  EventMaskObj->Set(v8::String::New("PropertyChange"), v8::Integer::New(4194304));
  EventMaskObj->Set(v8::String::New("ColorMapChange"), v8::Integer::New(8388608));
  EventMaskObj->Set(v8::String::New("OwnerGrabButton"), v8::Integer::New(16777216));
  v8::Local<v8::Object> BackingStoreObj = v8::Object::New();
  enums->Set(v8::String::New("BackingStore"), BackingStoreObj);
  BackingStoreObj->Set(v8::String::New("NotUseful"), v8::Integer::New(0));
  BackingStoreObj->Set(v8::String::New("WhenMapped"), v8::Integer::New(1));
  BackingStoreObj->Set(v8::String::New("Always"), v8::Integer::New(2));
  v8::Local<v8::Object> ImageOrderObj = v8::Object::New();
  enums->Set(v8::String::New("ImageOrder"), ImageOrderObj);
  ImageOrderObj->Set(v8::String::New("LSBFirst"), v8::Integer::New(0));
  ImageOrderObj->Set(v8::String::New("MSBFirst"), v8::Integer::New(1));
  v8::Local<v8::Object> ModMaskObj = v8::Object::New();
  enums->Set(v8::String::New("ModMask"), ModMaskObj);
  ModMaskObj->Set(v8::String::New("Shift"), v8::Integer::New(1));
  ModMaskObj->Set(v8::String::New("Lock"), v8::Integer::New(2));
  ModMaskObj->Set(v8::String::New("Control"), v8::Integer::New(4));
  ModMaskObj->Set(v8::String::New("1"), v8::Integer::New(8));
  ModMaskObj->Set(v8::String::New("2"), v8::Integer::New(16));
  ModMaskObj->Set(v8::String::New("3"), v8::Integer::New(32));
  ModMaskObj->Set(v8::String::New("4"), v8::Integer::New(64));
  ModMaskObj->Set(v8::String::New("5"), v8::Integer::New(128));
  ModMaskObj->Set(v8::String::New("Any"), v8::Integer::New(32768));
  v8::Local<v8::Object> KeyButMaskObj = v8::Object::New();
  enums->Set(v8::String::New("KeyButMask"), KeyButMaskObj);
  KeyButMaskObj->Set(v8::String::New("Shift"), v8::Integer::New(1));
  KeyButMaskObj->Set(v8::String::New("Lock"), v8::Integer::New(2));
  KeyButMaskObj->Set(v8::String::New("Control"), v8::Integer::New(4));
  KeyButMaskObj->Set(v8::String::New("Mod1"), v8::Integer::New(8));
  KeyButMaskObj->Set(v8::String::New("Mod2"), v8::Integer::New(16));
  KeyButMaskObj->Set(v8::String::New("Mod3"), v8::Integer::New(32));
  KeyButMaskObj->Set(v8::String::New("Mod4"), v8::Integer::New(64));
  KeyButMaskObj->Set(v8::String::New("Mod5"), v8::Integer::New(128));
  KeyButMaskObj->Set(v8::String::New("Button1"), v8::Integer::New(256));
  KeyButMaskObj->Set(v8::String::New("Button2"), v8::Integer::New(512));
  KeyButMaskObj->Set(v8::String::New("Button3"), v8::Integer::New(1024));
  KeyButMaskObj->Set(v8::String::New("Button4"), v8::Integer::New(2048));
  KeyButMaskObj->Set(v8::String::New("Button5"), v8::Integer::New(4096));
  v8::Local<v8::Object> WindowObj = v8::Object::New();
  enums->Set(v8::String::New("Window"), WindowObj);
  WindowObj->Set(v8::String::New("None"), v8::Integer::New(0));
  v8::Local<v8::Object> ButtonMaskObj = v8::Object::New();
  enums->Set(v8::String::New("ButtonMask"), ButtonMaskObj);
  ButtonMaskObj->Set(v8::String::New("1"), v8::Integer::New(256));
  ButtonMaskObj->Set(v8::String::New("2"), v8::Integer::New(512));
  ButtonMaskObj->Set(v8::String::New("3"), v8::Integer::New(1024));
  ButtonMaskObj->Set(v8::String::New("4"), v8::Integer::New(2048));
  ButtonMaskObj->Set(v8::String::New("5"), v8::Integer::New(4096));
  ButtonMaskObj->Set(v8::String::New("Any"), v8::Integer::New(32768));
  v8::Local<v8::Object> MotionObj = v8::Object::New();
  enums->Set(v8::String::New("Motion"), MotionObj);
  MotionObj->Set(v8::String::New("Normal"), v8::Integer::New(0));
  MotionObj->Set(v8::String::New("Hint"), v8::Integer::New(1));
  v8::Local<v8::Object> NotifyDetailObj = v8::Object::New();
  enums->Set(v8::String::New("NotifyDetail"), NotifyDetailObj);
  NotifyDetailObj->Set(v8::String::New("Ancestor"), v8::Integer::New(0));
  NotifyDetailObj->Set(v8::String::New("Virtual"), v8::Integer::New(1));
  NotifyDetailObj->Set(v8::String::New("Inferior"), v8::Integer::New(2));
  NotifyDetailObj->Set(v8::String::New("Nonlinear"), v8::Integer::New(3));
  NotifyDetailObj->Set(v8::String::New("NonlinearVirtual"), v8::Integer::New(4));
  NotifyDetailObj->Set(v8::String::New("Pointer"), v8::Integer::New(5));
  NotifyDetailObj->Set(v8::String::New("PointerRoot"), v8::Integer::New(6));
  NotifyDetailObj->Set(v8::String::New("None"), v8::Integer::New(7));
  v8::Local<v8::Object> NotifyModeObj = v8::Object::New();
  enums->Set(v8::String::New("NotifyMode"), NotifyModeObj);
  NotifyModeObj->Set(v8::String::New("Normal"), v8::Integer::New(0));
  NotifyModeObj->Set(v8::String::New("Grab"), v8::Integer::New(1));
  NotifyModeObj->Set(v8::String::New("Ungrab"), v8::Integer::New(2));
  NotifyModeObj->Set(v8::String::New("WhileGrabbed"), v8::Integer::New(3));
  v8::Local<v8::Object> VisibilityObj = v8::Object::New();
  enums->Set(v8::String::New("Visibility"), VisibilityObj);
  VisibilityObj->Set(v8::String::New("Unobscured"), v8::Integer::New(0));
  VisibilityObj->Set(v8::String::New("PartiallyObscured"), v8::Integer::New(1));
  VisibilityObj->Set(v8::String::New("FullyObscured"), v8::Integer::New(2));
  v8::Local<v8::Object> PlaceObj = v8::Object::New();
  enums->Set(v8::String::New("Place"), PlaceObj);
  PlaceObj->Set(v8::String::New("OnTop"), v8::Integer::New(0));
  PlaceObj->Set(v8::String::New("OnBottom"), v8::Integer::New(1));
  v8::Local<v8::Object> PropertyObj = v8::Object::New();
  enums->Set(v8::String::New("Property"), PropertyObj);
  PropertyObj->Set(v8::String::New("NewValue"), v8::Integer::New(0));
  PropertyObj->Set(v8::String::New("Delete"), v8::Integer::New(1));
  v8::Local<v8::Object> TimeObj = v8::Object::New();
  enums->Set(v8::String::New("Time"), TimeObj);
  TimeObj->Set(v8::String::New("CurrentTime"), v8::Integer::New(0));
  v8::Local<v8::Object> AtomObj = v8::Object::New();
  enums->Set(v8::String::New("Atom"), AtomObj);
  AtomObj->Set(v8::String::New("None"), v8::Integer::New(0));
  AtomObj->Set(v8::String::New("Any"), v8::Integer::New(0));
  AtomObj->Set(v8::String::New("PRIMARY"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("SECONDARY"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("ARC"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("ATOM"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("BITMAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CARDINAL"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("COLORMAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CURSOR"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER0"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER1"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER2"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER3"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER4"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER5"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER6"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CUT_BUFFER7"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("DRAWABLE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("FONT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("INTEGER"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("PIXMAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("POINT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RECTANGLE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RESOURCE_MANAGER"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_COLOR_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_BEST_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_BLUE_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_DEFAULT_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_GRAY_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_GREEN_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RGB_RED_MAP"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("STRING"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("VISUALID"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WINDOW"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_COMMAND"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_HINTS"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_CLIENT_MACHINE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_ICON_NAME"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_ICON_SIZE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_NAME"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_NORMAL_HINTS"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_SIZE_HINTS"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_ZOOM_HINTS"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("MIN_SPACE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("NORM_SPACE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("MAX_SPACE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("END_SPACE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("SUPERSCRIPT_X"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("SUPERSCRIPT_Y"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("SUBSCRIPT_X"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("SUBSCRIPT_Y"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("UNDERLINE_POSITION"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("UNDERLINE_THICKNESS"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("STRIKEOUT_ASCENT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("STRIKEOUT_DESCENT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("ITALIC_ANGLE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("X_HEIGHT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("QUAD_WIDTH"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WEIGHT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("POINT_SIZE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("RESOLUTION"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("COPYRIGHT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("NOTICE"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("FONT_NAME"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("FAMILY_NAME"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("FULL_NAME"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("CAP_HEIGHT"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_CLASS"), v8::Integer::New(1));
  AtomObj->Set(v8::String::New("WM_TRANSIENT_FOR"), v8::Integer::New(1));
  v8::Local<v8::Object> ColormapStateObj = v8::Object::New();
  enums->Set(v8::String::New("ColormapState"), ColormapStateObj);
  ColormapStateObj->Set(v8::String::New("Uninstalled"), v8::Integer::New(0));
  ColormapStateObj->Set(v8::String::New("Installed"), v8::Integer::New(1));
  v8::Local<v8::Object> ColormapObj = v8::Object::New();
  enums->Set(v8::String::New("Colormap"), ColormapObj);
  ColormapObj->Set(v8::String::New("None"), v8::Integer::New(0));
  v8::Local<v8::Object> MappingObj = v8::Object::New();
  enums->Set(v8::String::New("Mapping"), MappingObj);
  MappingObj->Set(v8::String::New("Modifier"), v8::Integer::New(0));
  MappingObj->Set(v8::String::New("Keyboard"), v8::Integer::New(1));
  MappingObj->Set(v8::String::New("Pointer"), v8::Integer::New(2));
  v8::Local<v8::Object> WindowClassObj = v8::Object::New();
  enums->Set(v8::String::New("WindowClass"), WindowClassObj);
  WindowClassObj->Set(v8::String::New("CopyFromParent"), v8::Integer::New(0));
  WindowClassObj->Set(v8::String::New("InputOutput"), v8::Integer::New(1));
  WindowClassObj->Set(v8::String::New("InputOnly"), v8::Integer::New(2));
  v8::Local<v8::Object> CWObj = v8::Object::New();
  enums->Set(v8::String::New("CW"), CWObj);
  CWObj->Set(v8::String::New("BackPixmap"), v8::Integer::New(1));
  CWObj->Set(v8::String::New("BackPixel"), v8::Integer::New(2));
  CWObj->Set(v8::String::New("BorderPixmap"), v8::Integer::New(4));
  CWObj->Set(v8::String::New("BorderPixel"), v8::Integer::New(8));
  CWObj->Set(v8::String::New("BitGravity"), v8::Integer::New(16));
  CWObj->Set(v8::String::New("WinGravity"), v8::Integer::New(32));
  CWObj->Set(v8::String::New("BackingStore"), v8::Integer::New(64));
  CWObj->Set(v8::String::New("BackingPlanes"), v8::Integer::New(128));
  CWObj->Set(v8::String::New("BackingPixel"), v8::Integer::New(256));
  CWObj->Set(v8::String::New("OverrideRedirect"), v8::Integer::New(512));
  CWObj->Set(v8::String::New("SaveUnder"), v8::Integer::New(1024));
  CWObj->Set(v8::String::New("EventMask"), v8::Integer::New(2048));
  CWObj->Set(v8::String::New("DontPropagate"), v8::Integer::New(4096));
  CWObj->Set(v8::String::New("Colormap"), v8::Integer::New(8192));
  CWObj->Set(v8::String::New("Cursor"), v8::Integer::New(16384));
  v8::Local<v8::Object> BackPixmapObj = v8::Object::New();
  enums->Set(v8::String::New("BackPixmap"), BackPixmapObj);
  BackPixmapObj->Set(v8::String::New("None"), v8::Integer::New(0));
  BackPixmapObj->Set(v8::String::New("ParentRelative"), v8::Integer::New(1));
  v8::Local<v8::Object> GravityObj = v8::Object::New();
  enums->Set(v8::String::New("Gravity"), GravityObj);
  GravityObj->Set(v8::String::New("BitForget"), v8::Integer::New(0));
  GravityObj->Set(v8::String::New("WinUnmap"), v8::Integer::New(0));
  GravityObj->Set(v8::String::New("NorthWest"), v8::Integer::New(1));
  GravityObj->Set(v8::String::New("North"), v8::Integer::New(2));
  GravityObj->Set(v8::String::New("NorthEast"), v8::Integer::New(3));
  GravityObj->Set(v8::String::New("West"), v8::Integer::New(4));
  GravityObj->Set(v8::String::New("Center"), v8::Integer::New(5));
  GravityObj->Set(v8::String::New("East"), v8::Integer::New(6));
  GravityObj->Set(v8::String::New("SouthWest"), v8::Integer::New(7));
  GravityObj->Set(v8::String::New("South"), v8::Integer::New(8));
  GravityObj->Set(v8::String::New("SouthEast"), v8::Integer::New(9));
  GravityObj->Set(v8::String::New("Static"), v8::Integer::New(10));
  v8::Local<v8::Object> MapStateObj = v8::Object::New();
  enums->Set(v8::String::New("MapState"), MapStateObj);
  MapStateObj->Set(v8::String::New("Unmapped"), v8::Integer::New(0));
  MapStateObj->Set(v8::String::New("Unviewable"), v8::Integer::New(1));
  MapStateObj->Set(v8::String::New("Viewable"), v8::Integer::New(2));
  v8::Local<v8::Object> SetModeObj = v8::Object::New();
  enums->Set(v8::String::New("SetMode"), SetModeObj);
  SetModeObj->Set(v8::String::New("Insert"), v8::Integer::New(0));
  SetModeObj->Set(v8::String::New("Delete"), v8::Integer::New(1));
  v8::Local<v8::Object> ConfigWindowObj = v8::Object::New();
  enums->Set(v8::String::New("ConfigWindow"), ConfigWindowObj);
  ConfigWindowObj->Set(v8::String::New("X"), v8::Integer::New(1));
  ConfigWindowObj->Set(v8::String::New("Y"), v8::Integer::New(2));
  ConfigWindowObj->Set(v8::String::New("Width"), v8::Integer::New(4));
  ConfigWindowObj->Set(v8::String::New("Height"), v8::Integer::New(8));
  ConfigWindowObj->Set(v8::String::New("BorderWidth"), v8::Integer::New(16));
  ConfigWindowObj->Set(v8::String::New("Sibling"), v8::Integer::New(32));
  ConfigWindowObj->Set(v8::String::New("StackMode"), v8::Integer::New(64));
  v8::Local<v8::Object> StackModeObj = v8::Object::New();
  enums->Set(v8::String::New("StackMode"), StackModeObj);
  StackModeObj->Set(v8::String::New("Above"), v8::Integer::New(0));
  StackModeObj->Set(v8::String::New("Below"), v8::Integer::New(1));
  StackModeObj->Set(v8::String::New("TopIf"), v8::Integer::New(2));
  StackModeObj->Set(v8::String::New("BottomIf"), v8::Integer::New(3));
  StackModeObj->Set(v8::String::New("Opposite"), v8::Integer::New(4));
  v8::Local<v8::Object> CirculateObj = v8::Object::New();
  enums->Set(v8::String::New("Circulate"), CirculateObj);
  CirculateObj->Set(v8::String::New("RaiseLowest"), v8::Integer::New(0));
  CirculateObj->Set(v8::String::New("LowerHighest"), v8::Integer::New(1));
  v8::Local<v8::Object> PropModeObj = v8::Object::New();
  enums->Set(v8::String::New("PropMode"), PropModeObj);
  PropModeObj->Set(v8::String::New("Replace"), v8::Integer::New(0));
  PropModeObj->Set(v8::String::New("Prepend"), v8::Integer::New(1));
  PropModeObj->Set(v8::String::New("Append"), v8::Integer::New(2));
  v8::Local<v8::Object> GetPropertyTypeObj = v8::Object::New();
  enums->Set(v8::String::New("GetPropertyType"), GetPropertyTypeObj);
  GetPropertyTypeObj->Set(v8::String::New("Any"), v8::Integer::New(0));
  v8::Local<v8::Object> SendEventDestObj = v8::Object::New();
  enums->Set(v8::String::New("SendEventDest"), SendEventDestObj);
  SendEventDestObj->Set(v8::String::New("PointerWindow"), v8::Integer::New(0));
  SendEventDestObj->Set(v8::String::New("ItemFocus"), v8::Integer::New(1));
  v8::Local<v8::Object> GrabModeObj = v8::Object::New();
  enums->Set(v8::String::New("GrabMode"), GrabModeObj);
  GrabModeObj->Set(v8::String::New("Sync"), v8::Integer::New(0));
  GrabModeObj->Set(v8::String::New("Async"), v8::Integer::New(1));
  v8::Local<v8::Object> GrabStatusObj = v8::Object::New();
  enums->Set(v8::String::New("GrabStatus"), GrabStatusObj);
  GrabStatusObj->Set(v8::String::New("Success"), v8::Integer::New(0));
  GrabStatusObj->Set(v8::String::New("AlreadyGrabbed"), v8::Integer::New(1));
  GrabStatusObj->Set(v8::String::New("InvalidTime"), v8::Integer::New(2));
  GrabStatusObj->Set(v8::String::New("NotViewable"), v8::Integer::New(3));
  GrabStatusObj->Set(v8::String::New("Frozen"), v8::Integer::New(4));
  v8::Local<v8::Object> CursorObj = v8::Object::New();
  enums->Set(v8::String::New("Cursor"), CursorObj);
  CursorObj->Set(v8::String::New("None"), v8::Integer::New(0));
  v8::Local<v8::Object> ButtonIndexObj = v8::Object::New();
  enums->Set(v8::String::New("ButtonIndex"), ButtonIndexObj);
  ButtonIndexObj->Set(v8::String::New("Any"), v8::Integer::New(0));
  ButtonIndexObj->Set(v8::String::New("1"), v8::Integer::New(1));
  ButtonIndexObj->Set(v8::String::New("2"), v8::Integer::New(2));
  ButtonIndexObj->Set(v8::String::New("3"), v8::Integer::New(3));
  ButtonIndexObj->Set(v8::String::New("4"), v8::Integer::New(4));
  ButtonIndexObj->Set(v8::String::New("5"), v8::Integer::New(5));
  v8::Local<v8::Object> GrabObj = v8::Object::New();
  enums->Set(v8::String::New("Grab"), GrabObj);
  GrabObj->Set(v8::String::New("Any"), v8::Integer::New(0));
  v8::Local<v8::Object> AllowObj = v8::Object::New();
  enums->Set(v8::String::New("Allow"), AllowObj);
  AllowObj->Set(v8::String::New("AsyncPointer"), v8::Integer::New(0));
  AllowObj->Set(v8::String::New("SyncPointer"), v8::Integer::New(1));
  AllowObj->Set(v8::String::New("ReplayPointer"), v8::Integer::New(2));
  AllowObj->Set(v8::String::New("AsyncKeyboard"), v8::Integer::New(3));
  AllowObj->Set(v8::String::New("SyncKeyboard"), v8::Integer::New(4));
  AllowObj->Set(v8::String::New("ReplayKeyboard"), v8::Integer::New(5));
  AllowObj->Set(v8::String::New("AsyncBoth"), v8::Integer::New(6));
  AllowObj->Set(v8::String::New("SyncBoth"), v8::Integer::New(7));
  v8::Local<v8::Object> InputFocusObj = v8::Object::New();
  enums->Set(v8::String::New("InputFocus"), InputFocusObj);
  InputFocusObj->Set(v8::String::New("None"), v8::Integer::New(0));
  InputFocusObj->Set(v8::String::New("PointerRoot"), v8::Integer::New(1));
  InputFocusObj->Set(v8::String::New("Parent"), v8::Integer::New(2));
  InputFocusObj->Set(v8::String::New("FollowKeyboard"), v8::Integer::New(3));
  v8::Local<v8::Object> FontDrawObj = v8::Object::New();
  enums->Set(v8::String::New("FontDraw"), FontDrawObj);
  FontDrawObj->Set(v8::String::New("LeftToRight"), v8::Integer::New(0));
  FontDrawObj->Set(v8::String::New("RightToLeft"), v8::Integer::New(1));
  v8::Local<v8::Object> GCObj = v8::Object::New();
  enums->Set(v8::String::New("GC"), GCObj);
  GCObj->Set(v8::String::New("Function"), v8::Integer::New(1));
  GCObj->Set(v8::String::New("PlaneMask"), v8::Integer::New(2));
  GCObj->Set(v8::String::New("Foreground"), v8::Integer::New(4));
  GCObj->Set(v8::String::New("Background"), v8::Integer::New(8));
  GCObj->Set(v8::String::New("LineWidth"), v8::Integer::New(16));
  GCObj->Set(v8::String::New("LineStyle"), v8::Integer::New(32));
  GCObj->Set(v8::String::New("CapStyle"), v8::Integer::New(64));
  GCObj->Set(v8::String::New("JoinStyle"), v8::Integer::New(128));
  GCObj->Set(v8::String::New("FillStyle"), v8::Integer::New(256));
  GCObj->Set(v8::String::New("FillRule"), v8::Integer::New(512));
  GCObj->Set(v8::String::New("Tile"), v8::Integer::New(1024));
  GCObj->Set(v8::String::New("Stipple"), v8::Integer::New(2048));
  GCObj->Set(v8::String::New("TileStippleOriginX"), v8::Integer::New(4096));
  GCObj->Set(v8::String::New("TileStippleOriginY"), v8::Integer::New(8192));
  GCObj->Set(v8::String::New("Font"), v8::Integer::New(16384));
  GCObj->Set(v8::String::New("SubwindowMode"), v8::Integer::New(32768));
  GCObj->Set(v8::String::New("GraphicsExposures"), v8::Integer::New(65536));
  GCObj->Set(v8::String::New("ClipOriginX"), v8::Integer::New(131072));
  GCObj->Set(v8::String::New("ClipOriginY"), v8::Integer::New(262144));
  GCObj->Set(v8::String::New("ClipMask"), v8::Integer::New(524288));
  GCObj->Set(v8::String::New("DashOffset"), v8::Integer::New(1048576));
  GCObj->Set(v8::String::New("DashList"), v8::Integer::New(2097152));
  GCObj->Set(v8::String::New("ArcMode"), v8::Integer::New(4194304));
  v8::Local<v8::Object> GXObj = v8::Object::New();
  enums->Set(v8::String::New("GX"), GXObj);
  GXObj->Set(v8::String::New("clear"), v8::Integer::New(0));
  GXObj->Set(v8::String::New("and"), v8::Integer::New(1));
  GXObj->Set(v8::String::New("andReverse"), v8::Integer::New(2));
  GXObj->Set(v8::String::New("copy"), v8::Integer::New(3));
  GXObj->Set(v8::String::New("andInverted"), v8::Integer::New(4));
  GXObj->Set(v8::String::New("noop"), v8::Integer::New(5));
  GXObj->Set(v8::String::New("xor"), v8::Integer::New(6));
  GXObj->Set(v8::String::New("or"), v8::Integer::New(7));
  GXObj->Set(v8::String::New("nor"), v8::Integer::New(8));
  GXObj->Set(v8::String::New("equiv"), v8::Integer::New(9));
  GXObj->Set(v8::String::New("invert"), v8::Integer::New(10));
  GXObj->Set(v8::String::New("orReverse"), v8::Integer::New(11));
  GXObj->Set(v8::String::New("copyInverted"), v8::Integer::New(12));
  GXObj->Set(v8::String::New("orInverted"), v8::Integer::New(13));
  GXObj->Set(v8::String::New("nand"), v8::Integer::New(14));
  GXObj->Set(v8::String::New("set"), v8::Integer::New(15));
  v8::Local<v8::Object> LineStyleObj = v8::Object::New();
  enums->Set(v8::String::New("LineStyle"), LineStyleObj);
  LineStyleObj->Set(v8::String::New("Solid"), v8::Integer::New(0));
  LineStyleObj->Set(v8::String::New("OnOffDash"), v8::Integer::New(1));
  LineStyleObj->Set(v8::String::New("DoubleDash"), v8::Integer::New(2));
  v8::Local<v8::Object> CapStyleObj = v8::Object::New();
  enums->Set(v8::String::New("CapStyle"), CapStyleObj);
  CapStyleObj->Set(v8::String::New("NotLast"), v8::Integer::New(0));
  CapStyleObj->Set(v8::String::New("Butt"), v8::Integer::New(1));
  CapStyleObj->Set(v8::String::New("Round"), v8::Integer::New(2));
  CapStyleObj->Set(v8::String::New("Projecting"), v8::Integer::New(3));
  v8::Local<v8::Object> JoinStyleObj = v8::Object::New();
  enums->Set(v8::String::New("JoinStyle"), JoinStyleObj);
  JoinStyleObj->Set(v8::String::New("Miter"), v8::Integer::New(0));
  JoinStyleObj->Set(v8::String::New("Round"), v8::Integer::New(1));
  JoinStyleObj->Set(v8::String::New("Bevel"), v8::Integer::New(2));
  v8::Local<v8::Object> FillStyleObj = v8::Object::New();
  enums->Set(v8::String::New("FillStyle"), FillStyleObj);
  FillStyleObj->Set(v8::String::New("Solid"), v8::Integer::New(0));
  FillStyleObj->Set(v8::String::New("Tiled"), v8::Integer::New(1));
  FillStyleObj->Set(v8::String::New("Stippled"), v8::Integer::New(2));
  FillStyleObj->Set(v8::String::New("OpaqueStippled"), v8::Integer::New(3));
  v8::Local<v8::Object> FillRuleObj = v8::Object::New();
  enums->Set(v8::String::New("FillRule"), FillRuleObj);
  FillRuleObj->Set(v8::String::New("EvenOdd"), v8::Integer::New(0));
  FillRuleObj->Set(v8::String::New("Winding"), v8::Integer::New(1));
  v8::Local<v8::Object> SubwindowModeObj = v8::Object::New();
  enums->Set(v8::String::New("SubwindowMode"), SubwindowModeObj);
  SubwindowModeObj->Set(v8::String::New("ClipByChildren"), v8::Integer::New(0));
  SubwindowModeObj->Set(v8::String::New("IncludeInferiors"), v8::Integer::New(1));
  v8::Local<v8::Object> ArcModeObj = v8::Object::New();
  enums->Set(v8::String::New("ArcMode"), ArcModeObj);
  ArcModeObj->Set(v8::String::New("Chord"), v8::Integer::New(0));
  ArcModeObj->Set(v8::String::New("PieSlice"), v8::Integer::New(1));
  v8::Local<v8::Object> ClipOrderingObj = v8::Object::New();
  enums->Set(v8::String::New("ClipOrdering"), ClipOrderingObj);
  ClipOrderingObj->Set(v8::String::New("Unsorted"), v8::Integer::New(0));
  ClipOrderingObj->Set(v8::String::New("YSorted"), v8::Integer::New(1));
  ClipOrderingObj->Set(v8::String::New("YXSorted"), v8::Integer::New(2));
  ClipOrderingObj->Set(v8::String::New("YXBanded"), v8::Integer::New(3));
  v8::Local<v8::Object> CoordModeObj = v8::Object::New();
  enums->Set(v8::String::New("CoordMode"), CoordModeObj);
  CoordModeObj->Set(v8::String::New("Origin"), v8::Integer::New(0));
  CoordModeObj->Set(v8::String::New("Previous"), v8::Integer::New(1));
  v8::Local<v8::Object> PolyShapeObj = v8::Object::New();
  enums->Set(v8::String::New("PolyShape"), PolyShapeObj);
  PolyShapeObj->Set(v8::String::New("Complex"), v8::Integer::New(0));
  PolyShapeObj->Set(v8::String::New("Nonconvex"), v8::Integer::New(1));
  PolyShapeObj->Set(v8::String::New("Convex"), v8::Integer::New(2));
  v8::Local<v8::Object> ImageFormatObj = v8::Object::New();
  enums->Set(v8::String::New("ImageFormat"), ImageFormatObj);
  ImageFormatObj->Set(v8::String::New("XYBitmap"), v8::Integer::New(0));
  ImageFormatObj->Set(v8::String::New("XYPixmap"), v8::Integer::New(1));
  ImageFormatObj->Set(v8::String::New("ZPixmap"), v8::Integer::New(2));
  v8::Local<v8::Object> ColormapAllocObj = v8::Object::New();
  enums->Set(v8::String::New("ColormapAlloc"), ColormapAllocObj);
  ColormapAllocObj->Set(v8::String::New("None"), v8::Integer::New(0));
  ColormapAllocObj->Set(v8::String::New("All"), v8::Integer::New(1));
  v8::Local<v8::Object> ColorFlagObj = v8::Object::New();
  enums->Set(v8::String::New("ColorFlag"), ColorFlagObj);
  ColorFlagObj->Set(v8::String::New("Red"), v8::Integer::New(1));
  ColorFlagObj->Set(v8::String::New("Green"), v8::Integer::New(2));
  ColorFlagObj->Set(v8::String::New("Blue"), v8::Integer::New(4));
  v8::Local<v8::Object> PixmapObj = v8::Object::New();
  enums->Set(v8::String::New("Pixmap"), PixmapObj);
  PixmapObj->Set(v8::String::New("None"), v8::Integer::New(0));
  v8::Local<v8::Object> FontObj = v8::Object::New();
  enums->Set(v8::String::New("Font"), FontObj);
  FontObj->Set(v8::String::New("None"), v8::Integer::New(0));
  v8::Local<v8::Object> QueryShapeOfObj = v8::Object::New();
  enums->Set(v8::String::New("QueryShapeOf"), QueryShapeOfObj);
  QueryShapeOfObj->Set(v8::String::New("LargestCursor"), v8::Integer::New(0));
  QueryShapeOfObj->Set(v8::String::New("FastestTile"), v8::Integer::New(1));
  QueryShapeOfObj->Set(v8::String::New("FastestStipple"), v8::Integer::New(2));
  v8::Local<v8::Object> KBObj = v8::Object::New();
  enums->Set(v8::String::New("KB"), KBObj);
  KBObj->Set(v8::String::New("KeyClickPercent"), v8::Integer::New(1));
  KBObj->Set(v8::String::New("BellPercent"), v8::Integer::New(2));
  KBObj->Set(v8::String::New("BellPitch"), v8::Integer::New(4));
  KBObj->Set(v8::String::New("BellDuration"), v8::Integer::New(8));
  KBObj->Set(v8::String::New("Led"), v8::Integer::New(16));
  KBObj->Set(v8::String::New("LedMode"), v8::Integer::New(32));
  KBObj->Set(v8::String::New("Key"), v8::Integer::New(64));
  KBObj->Set(v8::String::New("AutoRepeatMode"), v8::Integer::New(128));
  v8::Local<v8::Object> LedModeObj = v8::Object::New();
  enums->Set(v8::String::New("LedMode"), LedModeObj);
  LedModeObj->Set(v8::String::New("Off"), v8::Integer::New(0));
  LedModeObj->Set(v8::String::New("On"), v8::Integer::New(1));
  v8::Local<v8::Object> AutoRepeatModeObj = v8::Object::New();
  enums->Set(v8::String::New("AutoRepeatMode"), AutoRepeatModeObj);
  AutoRepeatModeObj->Set(v8::String::New("Off"), v8::Integer::New(0));
  AutoRepeatModeObj->Set(v8::String::New("On"), v8::Integer::New(1));
  AutoRepeatModeObj->Set(v8::String::New("Default"), v8::Integer::New(2));
  v8::Local<v8::Object> BlankingObj = v8::Object::New();
  enums->Set(v8::String::New("Blanking"), BlankingObj);
  BlankingObj->Set(v8::String::New("NotPreferred"), v8::Integer::New(0));
  BlankingObj->Set(v8::String::New("Preferred"), v8::Integer::New(1));
  BlankingObj->Set(v8::String::New("Default"), v8::Integer::New(2));
  v8::Local<v8::Object> ExposuresObj = v8::Object::New();
  enums->Set(v8::String::New("Exposures"), ExposuresObj);
  ExposuresObj->Set(v8::String::New("NotAllowed"), v8::Integer::New(0));
  ExposuresObj->Set(v8::String::New("Allowed"), v8::Integer::New(1));
  ExposuresObj->Set(v8::String::New("Default"), v8::Integer::New(2));
  v8::Local<v8::Object> HostModeObj = v8::Object::New();
  enums->Set(v8::String::New("HostMode"), HostModeObj);
  HostModeObj->Set(v8::String::New("Insert"), v8::Integer::New(0));
  HostModeObj->Set(v8::String::New("Delete"), v8::Integer::New(1));
  v8::Local<v8::Object> FamilyObj = v8::Object::New();
  enums->Set(v8::String::New("Family"), FamilyObj);
  FamilyObj->Set(v8::String::New("Internet"), v8::Integer::New(0));
  FamilyObj->Set(v8::String::New("DECnet"), v8::Integer::New(1));
  FamilyObj->Set(v8::String::New("Chaos"), v8::Integer::New(2));
  FamilyObj->Set(v8::String::New("ServerInterpreted"), v8::Integer::New(5));
  FamilyObj->Set(v8::String::New("Internet6"), v8::Integer::New(6));
  v8::Local<v8::Object> AccessControlObj = v8::Object::New();
  enums->Set(v8::String::New("AccessControl"), AccessControlObj);
  AccessControlObj->Set(v8::String::New("Disable"), v8::Integer::New(0));
  AccessControlObj->Set(v8::String::New("Enable"), v8::Integer::New(1));
  v8::Local<v8::Object> CloseDownObj = v8::Object::New();
  enums->Set(v8::String::New("CloseDown"), CloseDownObj);
  CloseDownObj->Set(v8::String::New("DestroyAll"), v8::Integer::New(0));
  CloseDownObj->Set(v8::String::New("RetainPermanent"), v8::Integer::New(1));
  CloseDownObj->Set(v8::String::New("RetainTemporary"), v8::Integer::New(2));
  v8::Local<v8::Object> KillObj = v8::Object::New();
  enums->Set(v8::String::New("Kill"), KillObj);
  KillObj->Set(v8::String::New("AllTemporary"), v8::Integer::New(0));
  v8::Local<v8::Object> ScreenSaverObj = v8::Object::New();
  enums->Set(v8::String::New("ScreenSaver"), ScreenSaverObj);
  ScreenSaverObj->Set(v8::String::New("Reset"), v8::Integer::New(0));
  ScreenSaverObj->Set(v8::String::New("Active"), v8::Integer::New(1));
  v8::Local<v8::Object> MappingStatusObj = v8::Object::New();
  enums->Set(v8::String::New("MappingStatus"), MappingStatusObj);
  MappingStatusObj->Set(v8::String::New("Success"), v8::Integer::New(0));
  MappingStatusObj->Set(v8::String::New("Busy"), v8::Integer::New(1));
  MappingStatusObj->Set(v8::String::New("Failure"), v8::Integer::New(2));
  v8::Local<v8::Object> MapIndexObj = v8::Object::New();
  enums->Set(v8::String::New("MapIndex"), MapIndexObj);
  MapIndexObj->Set(v8::String::New("Shift"), v8::Integer::New(0));
  MapIndexObj->Set(v8::String::New("Lock"), v8::Integer::New(1));
  MapIndexObj->Set(v8::String::New("Control"), v8::Integer::New(2));
  MapIndexObj->Set(v8::String::New("1"), v8::Integer::New(3));
  MapIndexObj->Set(v8::String::New("2"), v8::Integer::New(4));
  MapIndexObj->Set(v8::String::New("3"), v8::Integer::New(5));
  MapIndexObj->Set(v8::String::New("4"), v8::Integer::New(6));
  MapIndexObj->Set(v8::String::New("5"), v8::Integer::New(7));
}
  }
}

#endif